In [1]:
#NumPy

In [2]:
#Linear Algebra Library for Python

In [3]:
conda install numpy

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.0                |           py37_1         2.8 MB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.0-py37_1



conda-4.8.0          | 2.8 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.


In [1]:
#numpy arrays, vectors are 1-d arrays and matrices are 2-d

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
my_mat = [[1,2,3],[4,5,6], [7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [18]:
#Identity Matrix, two dimensional square matrix with same number of rows and columns with 1's as the diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#random numbers from uniform distribution

In [19]:
np.random.rand()

0.7613316451498711

In [20]:
np.random.rand(5)

array([0.39517254, 0.94070819, 0.24320366, 0.83908163, 0.22067835])

In [21]:
np.random.rand(5,6)

array([[0.03718186, 0.48302741, 0.32513797, 0.02939467, 0.47686428,
        0.32324356],
       [0.91728067, 0.32330334, 0.7857728 , 0.30227531, 0.02387027,
        0.3607878 ],
       [0.32157361, 0.76376019, 0.50195454, 0.64598127, 0.53963454,
        0.26453791],
       [0.91594349, 0.04540517, 0.31214566, 0.16020859, 0.5682016 ,
        0.89422739],
       [0.80611928, 0.33627591, 0.68336432, 0.81846355, 0.11695317,
        0.14015577]])

In [23]:
#two random numbers from the standard normal distribution
np.random.randn(2)

array([0.11656064, 0.40866256])

In [24]:
np.random.randn(4,4)

array([[ 0.71102052,  1.88148915,  3.05890641, -0.21872932],
       [ 0.71901436, -1.47857844, -0.04644631, -0.13316462],
       [ 0.0537545 ,  0.96840729, -1.98215177, -0.84313721],
       [ 0.01099815,  0.93409164, -0.82236851, -0.56113551]])

In [26]:
np.random.randint(1,57,5)

array([48, 28, 33,  9,  4])

In [4]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([38, 40, 42, 49,  6, 28, 21,  2,  1,  4])

In [31]:
ranarr.max()

49

In [32]:
ranarr.min()

1

In [33]:
ranarr

array([38, 40, 42, 49,  6, 28, 21,  2,  1,  4])

In [34]:
#index location of the max value
ranarr.argmax()

3

In [35]:
#datatype of an array
arr.dtype

dtype('int64')

In [37]:
from numpy.random import randint

In [38]:
randint(2,10)

7

In [39]:
#NUMPY INDEXING AND SELECTION


In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[5]

5

In [42]:
arr[1:4]

array([1, 2, 3])

In [43]:
arr[0:5] = 100

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)

In [46]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr = arr[0:6]

In [48]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [49]:
slice_of_arr[:] = 99

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
#the change occurs on the original array


In [52]:
arr_copy = arr.copy()


In [53]:
arr_copy[:] = 100

In [54]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
#2D Arrays


In [56]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [57]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr2d[0,0]

5

In [59]:
arr2d[0][0]

5

In [60]:
arr2d[2,1]

40

In [61]:
arr2d[1,2]

30

In [62]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
 arr = np.arange(1,11)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [66]:
boo = arr > 5

In [69]:
arr[boo]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr<3]

array([1, 2])

In [72]:
arr_2d = np.arange(50).reshape(5,10)

In [73]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [74]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [75]:
##NUMPY OPERATIONS

In [76]:
#Array with Array operations
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [81]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [83]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [84]:
1/0

ZeroDivisionError: division by zero

In [85]:
arr / arr

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [87]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [88]:
np.max(arr)

10

In [89]:
arr.max()

10

In [90]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [91]:
np.exp(arr,5)

TypeError: return arrays must be of ArrayType

In [92]:
np.power(arr,3)

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])